baseURL = 'https://furkancansever.xyz/'
languageCode = 'en-us'
title = "hi, i'm furkan."
theme = 'hello-friend-ng'

[params]
  homeSubtitle = "( ͡° ͜ʖ ͡°)"

[params.footer]
  topText = ["Furkan Cansever", "<a href='mailto:furkancansever@icloud.com'>furkancansever@icloud.com</a>"]
  bottomText = [
    "<br>Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"
  ]

[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "Athoughts"
    name       = "Thoughts"
    url        = "thoughts/"
  [[menu.main]]
    identifier = "bookmarks"
    name       = "Bookmarks"
    url        = "bookmarks/"

[[params.social]]
name = "email"
url  = "mailto:furkan.cansever@icloud.com"

[[params.social]]
name = "github"
url  = "https://github.com/cnsvr"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/furkan-cansever"